name: "Unconditional"
description: "Check a codebase for conditional logic"
inputs:
  include: # globs of files to include, space seperated
    description: "Glob patterns for files to include in the search"
    required: true
    default: "**/*"
  exclude: # globs of files to exclude, space seperated
    description: "Glob patterns for files to be excluded from the search"
    required: false
    default: ""
  conditionalLayer: # globs of files allowed to contain conditionals, space seperated
    description: "Glob patterns for the files in which your conditionals reside"
    required: false
    default: ""
  max: # maximum number of conditionals, as a string
    description: "The maximum number of conditionals allowed in a given file"
    required: false
    default: "0"
runs:
  using: "node12"
  main: "bundle/index.js"
