on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Unconditional
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Find Conditionals
        uses: gabrielbarker/Unconditional@v1.0.0
        with:
          include: "/src/**/*.ts"
          conditionalLayer: "/src/**/*.test.ts"
          max: "1"
